# ===============================
# Site metadata
# ===============================
title: Molecular Oncology Almanac
url: https://news.moalmanac.org
home_url: https://dev.moalmanac.org
github_url: https://github.com/vanallenlab/moalmanac-news

# ===============================
# Theme & Plugins
# ===============================
theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# ===============================
# Theme-specific options
# ===============================
minima:
  date_format: "%Y-%m-%d"

# ===============================
# Navigation (right side of header)
# Access in templates via `site.nav_right`
# ===============================
header_external_links:
  - title: About
    url: https://moalmanac.org/about
  - title: Contact
    url: https://dev.moalmanac.org
  - title: News
    url: /

# ===============================
# Content & Collections
# ===============================
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      published: true

# ===============================
# Writing & Rendering
# ===============================
show_excerpts: true

# ===============================
# Pagination
# ===============================
paginate: 5
paginate_path: "/page:num"

# ===============================
# Sass / SCSS
# ===============================
sass:
  quiet_deps: true

# ===============================
# Include / Exclude (build hygiene)
# ===============================
exclude:
  - utils/
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle/
  - .idea/
  - .jekyll-cache/
  - .gitignore

# ===============================
# Server (local dev)
# ===============================
host: 127.0.0.1
port: 4000
livereload: true
