title: Molecular Oncology Almanac

theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

minima:
  date_format: "%Y-%m-%d"

nav_right:
  - title: About
    url: https://moalmanac.org/about
  - title: Contact
    url: https://dev.moalmanac.org
  - title: News
    url: /

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      published: true

show_excerpts: true

paginate: 5
paginate_path: "/page:num"
